FROM python:3.9-slim

WORKDIR /app

COPY etl_model_api .

COPY src/ /app/src

COPY pyproject.toml .


RUN pip install --no-cache-dir -r requirements.txt

RUN pip install /app/src

CMD ["python3", "main.py"]