FROM python:3.9-slim

WORKDIR /app

COPY ./etl_model_api /app/

COPY ./src /app/src

COPY pyproject.toml /app/

RUN pip install -r requirments.txt

RUN pip install /app/src

CMD ['python',"-m", "/app/main.py"]