FROM python:3.9

WORKDIR /app

COPY ./api .

COPY src/ ./src

COPY pyproject.toml .

RUN pip install --no-cache-dir -r requirements.txt

RUN pip install .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

